Dom with javac may13
eclipse-jdtls/eclipse-jdt-core-incubator pull request #393
Opened 2024-05-16 20:42 UTC by robstryker

2024-05-17 06:00 UTC, mickaelistria requested changes
@datho7561 introduced `canonicalized` that seems to fix some issues as some tests (and probably some "functional" code does use identity comparison for bindings). Please use it whenever constructing a new binding.

2024-05-17 06:00 UTC, mickaelistria commented on org.eclipse.jdt.core.javac/src/org/eclipse/jdt/internal/javac/dom/JavacModuleBinding.java
> +			arr2[i] = new JavacModuleBinding((ModuleType)arr[i].module.type, this.resolver);
this should be `canonicalize(new ...)`

2024-05-17 06:00 UTC, mickaelistria commented on org.eclipse.jdt.core.javac/src/org/eclipse/jdt/internal/javac/dom/JavacModuleBinding.java
> +			JavacPackageBinding tmp = new JavacPackageBinding((PackageSymbol)arr[i].packge, this.resolver);
this should be `canonicalize(new ...)`

2024-05-17 06:00 UTC, mickaelistria commented on org.eclipse.jdt.core.javac/src/org/eclipse/jdt/internal/javac/dom/JavacModuleBinding.java
> +			arr2[i] = new JavacPackageBinding((PackageSymbol)arr[i].packge, this.resolver);
this should be `canonicalize(new ...)`

2024-05-17 06:00 UTC, mickaelistria commented on org.eclipse.jdt.core.javac/src/org/eclipse/jdt/internal/javac/dom/JavacModuleBinding.java
> +			arr2[i] = new JavacTypeBinding(arr[i].getService().type, this.resolver);
this should be `canonicalize(new ...)`

2024-05-17 06:00 UTC, mickaelistria commented on org.eclipse.jdt.core.javac/src/org/eclipse/jdt/internal/javac/dom/JavacModuleBinding.java
> +			arr2[i] = new JavacTypeBinding(arr[i].getService().type, this.resolver);
this should be `canonicalize(new ...)`

2024-05-17 06:00 UTC, mickaelistria commented on org.eclipse.jdt.core.javac/src/org/eclipse/jdt/internal/javac/dom/JavacModuleBinding.java
> +				JavacTypeBinding[] ret = arr[i].getImplementations().stream().map(x -> new JavacTypeBinding((ClassType)x.type, this.resolver)).toArray(JavacTypeBinding[]::new);
this should be `canonicalize(new ...)`

2024-05-17 06:00 UTC, mickaelistria commented on org.eclipse.jdt.core.javac/src/org/eclipse/jdt/internal/javac/dom/JavacPackageBinding.java
> +		return new JavacModuleBinding(this.packageSymbol.modle, this.resolver);
this should be `canonicalize(new ...)`

2024-05-17 06:00 UTC, mickaelistria commented on org.eclipse.jdt.core.javac/src/org/eclipse/jdt/internal/javac/dom/JavacTypeBinding.java
> +			l.add(new JavacTypeBinding(z1, this.resolver));
this should be `canonicalize(new ...)`

2024-05-17 06:00 UTC, mickaelistria commented on org.eclipse.jdt.core.javac/src/org/eclipse/jdt/internal/javac/dom/JavacTypeBinding.java
> +				l.add(this.resolver.canonicalize(new JavacTypeBinding(z2.get(i), this.resolver)));
this should be `canonicalize(new ...)`

2024-05-17 06:00 UTC, mickaelistria commented on org.eclipse.jdt.core.javac/src/org/eclipse/jdt/internal/javac/dom/JavacTypeBinding.java
> +			return new JavacModuleBinding(ps.modle, this.resolver);
this should be `canonicalize(new ...)`

2024-05-21 08:05 UTC, mickaelistria requested changes
Some missing canonicalize.
But everything else seems good.

2024-05-21 08:05 UTC, mickaelistria commented on org.eclipse.jdt.core.javac/src/org/eclipse/jdt/internal/javac/dom/JavacModuleBinding.java
> +		return list.stream().map((x) -> new JavacAnnotationBinding(x, this.resolver, this)).toArray(JavacAnnotationBinding[]::new);
this needs also `.map(resolver::canonicalize)`

2024-05-21 08:05 UTC, mickaelistria commented on org.eclipse.jdt.core.javac/src/org/eclipse/jdt/core/dom/JavacBindingResolver.java
> +			return new JavacTypeBinding(jcClassDecl.type, this);
This should call `resolver.canonicalize(...)`

2024-05-21 08:05 UTC, mickaelistria commented on org.eclipse.jdt.core.javac/src/org/eclipse/jdt/internal/javac/dom/JavacModuleBinding.java
> +			arr2[i] = new JavacPackageBinding((PackageSymbol)arr[i].packge, this.resolver);
this should be canonicalize(new ...)

2024-05-21 17:42 UTC, robstryker commented
Merging without canocolization... we will revisit that.  It's a good point but i've had some issues and am hesitant to add that part at this moment.

2024-05-21 17:42 UTC, merged

2024-05-21 19:27 UTC, mickaelistria commented
We will revisit it as part of #395