[WIP] change how qualified types are handled
eclipse-jdtls/eclipse-jdt-core-incubator pull request #91
Opened 2024-02-22 18:39 UTC by datho7561

2024-02-23 07:35 UTC, mickaelistria requested changes

2024-02-23 07:35 UTC, mickaelistria commented on org.eclipse.jdt.core/model/org/eclipse/jdt/internal/core/CompilationUnit.java
> +}
There is a trick here: imagine one type `new SomeParentType.SomeNestedType((SomeRandomOtherType)null, (YetAnotherRandomOtherType)null)`, then with the change, all the types would then lead to their constructor definition, while in practice, we'd only want it if selecting the `SomeNestedType`. So additional checks are necessary.

2024-02-23 07:39 UTC, mickaelistria commented
The first change, fixing Util.getSignature() is a JDT bug. Can you please report it to JDT and make it a JDT PR? Then add it to our "blockers" tracker: https://github.com/orgs/eclipse-jdtls/projects/1/views/1 ?

2024-02-23 09:28 UTC, mickaelistria commented
The part about constructor binding was addressed in https://github.com/eclipse-jdtls/eclipse-jdt-core-incubator/pull/92
The bit about Signature should be reported and considered upstream (and then we'll cherry-pick it)

2024-02-24 09:40 UTC, mickaelistria commented
As I've merged an equivalent patch that includes support for Constructor special case, I've rebased the qualifier patch and submitted it in a dedicated PR to get an idea of what it fixes: https://github.com/eclipse-jdtls/eclipse-jdt-core-incubator/pull/96

2024-02-24 09:40 UTC, closed without merging

2024-02-28 15:38 UTC, datho7561 commented
> Then add it to our "blockers" tracker: https://github.com/orgs/eclipse-jdtls/projects/1/views/1 ?

@mickaelistria here is the upstream issue: https://github.com/eclipse-jdt/eclipse.jdt.core/issues/2074 .
I can't seem to add it to the board, I probably would need committership on eclipse.jdt.ls in order to do that.