Fix some errors that occur when importing o.e.j.c incubator
eclipse-jdtls/eclipse-jdt-core-incubator pull request #918
Opened 2024-10-31 16:07 UTC by datho7561

- Do not reuse the context when compiling to multiple output directories
- Implement Alex's idea of a separate file of javac-specific error codes

2024-10-31 19:19 UTC, datho7561 commented
All the regressions are caused by 'possible this escape' errors, which are now reported

2024-11-06 22:38 UTC, mickaelistria commented
Can you please split it into 2 distinct commits for each part of the change? I think the context bit is more risky than the problems mapping bit there are chances we'll have to revert it. Smaller commits allows less loss during reverts.

2024-11-07 14:23 UTC, datho7561 commented
I created a separate PR for the problem id changes.

2024-11-07 14:31 UTC, datho7561 commented
test this please

2024-11-13 14:52 UTC, mickaelistria commented on org.eclipse.jdt.core.javac/src/org/eclipse/jdt/core/dom/JavacBindingResolver.java
> +			}
I don't think this change is related. Can you please move it away from this PR?

2024-11-13 15:07 UTC, mickaelistria requested changes
The JavacCompiler changes would fix https://github.com/eclipse-jdtls/eclipse-jdt-core-incubator/issues/839 . Can you please move the probably unrelated part about bindings?

2024-11-13 15:13 UTC, datho7561 commented on org.eclipse.jdt.core.javac/src/org/eclipse/jdt/core/dom/JavacBindingResolver.java
> +			}
working on it...

2024-11-13 15:15 UTC, datho7561 commented on org.eclipse.jdt.core.javac/src/org/eclipse/jdt/core/dom/JavacBindingResolver.java
> +			}
see https://github.com/eclipse-jdtls/eclipse-jdt-core-incubator/pull/944

2024-11-14 12:24 UTC, merged

2024-11-14 12:26 UTC, mickaelistria commented
Thanks!